name: Run J Unit Tests
on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:
jobs:
  run-j-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "21"
      - name: run-unit-tests
        run: |
          cd backend
          ./gradlew test
