name: Validate Code
on:
  pull_request:
    types: [opened, reopened]
    branches: [ "main" ]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run unit tests
        run: |
          cd backend
          ./gradlew test